BEGIN TRANSACTION;
DROP TABLE IF EXISTS "Customer";
CREATE TABLE IF NOT EXISTS "Customer" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Company"	TEXT,
	"Notes"	TEXT,
	"DateCreated"	TEXT NOT NULL,
	PRIMARY KEY("Id"),
	UNIQUE("Company","Name")
);
DROP TABLE IF EXISTS "Operation";
CREATE TABLE IF NOT EXISTS "Operation" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Description"	TEXT NOT NULL,
	"Charge"	REAL NOT NULL DEFAULT 0,
	"CustomerId"	INTEGER NOT NULL,
	"DateCreated"	TEXT NOT NULL,
	"IsCompleted"	NUMERIC NOT NULL DEFAULT 0,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
COMMIT;
